-- MySQL Script generated by MySQL Workbench
-- 09/09/17 08:53:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsistemacafe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbsistemacafe` ;

-- -----------------------------------------------------
-- Schema dbsistemacafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsistemacafe` DEFAULT CHARACTER SET utf8 ;
USE `dbsistemacafe` ;

-- -----------------------------------------------------
-- Table `dbsistemacafe`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `apellidos` VARCHAR(40) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(10) NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `tipo` ENUM('MICRO', 'MEDIANO', 'GRANDE', 'GIGANTE') NOT NULL,
  `fechaInscripcion` DATE NULL,
  `usuario` VARCHAR(10) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemacafe`.`Finca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`Finca` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`Finca` (
  `idFinca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tamaño` DECIMAL NULL,
  `descripcion` TEXT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idFinca`),
  UNIQUE INDEX `idFinca_UNIQUE` (`idFinca` ASC),
  INDEX `fk_Finca_Cliente1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Finca_Cliente1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `dbsistemacafe`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemacafe`.`LocalizacionFinca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`LocalizacionFinca` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`LocalizacionFinca` (
  `idLocalizacion` INT NOT NULL AUTO_INCREMENT,
  `canton` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `distrito` VARCHAR(45) NOT NULL,
  `Finca_idFinca` INT NOT NULL,
  PRIMARY KEY (`idLocalizacion`),
  UNIQUE INDEX `idGeolocalizacion_UNIQUE` (`idLocalizacion` ASC),
  INDEX `fk_Geolocalizacion_Finca1_idx` (`Finca_idFinca` ASC),
  CONSTRAINT `fk_Geolocalizacion_Finca1`
    FOREIGN KEY (`Finca_idFinca`)
    REFERENCES `dbsistemacafe`.`Finca` (`idFinca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemacafe`.`Lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`Lote` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`Lote` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tamaño` DECIMAL NULL,
  `Lotecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idLote`),
  UNIQUE INDEX `idLote_UNIQUE` (`idLote` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemacafe`.`GeolocalizacionLote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`GeolocalizacionLote` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`GeolocalizacionLote` (
  `idGeolocalizacionLote` INT NOT NULL AUTO_INCREMENT,
  `latitud` DOUBLE NOT NULL,
  `longitud` DOUBLE NOT NULL,
  `Lote_idLote` INT NOT NULL,
  PRIMARY KEY (`idGeolocalizacionLote`),
  UNIQUE INDEX `idGeolocalizacionLote_UNIQUE` (`idGeolocalizacionLote` ASC),
  INDEX `fk_GeolocalizacionLote_Lote1_idx` (`Lote_idLote` ASC),
  CONSTRAINT `fk_GeolocalizacionLote_Lote1`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `dbsistemacafe`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemacafe`.`ProductosInsumos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`ProductosInsumos` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`ProductosInsumos` (
  `idProductosInsumos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad` DECIMAL NULL,
  `fecha` DATE NULL,
  `precio` DECIMAL NULL,
  PRIMARY KEY (`idProductosInsumos`),
  UNIQUE INDEX `idProductosInsumos_UNIQUE` (`idProductosInsumos` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemacafe`.`ProductosInsumos_has_Lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`ProductosInsumos_has_Lote` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`ProductosInsumos_has_Lote` (
  `ProductosInsumos_idProductosInsumos` INT NOT NULL,
  `Lote_idLote` INT NOT NULL,
  PRIMARY KEY (`ProductosInsumos_idProductosInsumos`, `Lote_idLote`),
  INDEX `fk_ProductosInsumos_has_Lote_Lote1_idx` (`Lote_idLote` ASC),
  INDEX `fk_ProductosInsumos_has_Lote_ProductosInsumos1_idx` (`ProductosInsumos_idProductosInsumos` ASC),
  CONSTRAINT `fk_ProductosInsumos_has_Lote_ProductosInsumos1`
    FOREIGN KEY (`ProductosInsumos_idProductosInsumos`)
    REFERENCES `dbsistemacafe`.`ProductosInsumos` (`idProductosInsumos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosInsumos_has_Lote_Lote1`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `dbsistemacafe`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemacafe`.`Trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`Trabajador` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`Trabajador` (
  `idTrabajador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `direccion` TEXT NULL,
  `cedula` VARCHAR(45) NULL,
  `deposito` DECIMAL NOT NULL,
  `Finca_idFinca` INT NOT NULL,
  PRIMARY KEY (`idTrabajador`),
  UNIQUE INDEX `idTrabajador_UNIQUE` (`idTrabajador` ASC),
  INDEX `fk_Trabajador_Finca1_idx` (`Finca_idFinca` ASC),
  CONSTRAINT `fk_Trabajador_Finca1`
    FOREIGN KEY (`Finca_idFinca`)
    REFERENCES `dbsistemacafe`.`Finca` (`idFinca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemacafe`.`Pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`Pagos` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`Pagos` (
  `idPagos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `pagoColones` DECIMAL NOT NULL,
  `Trabajador_idTrabajador` INT NOT NULL,
  PRIMARY KEY (`idPagos`),
  UNIQUE INDEX `idPagos_UNIQUE` (`idPagos` ASC),
  INDEX `fk_Pagos_Trabajador1_idx` (`Trabajador_idTrabajador` ASC),
  CONSTRAINT `fk_Pagos_Trabajador1`
    FOREIGN KEY (`Trabajador_idTrabajador`)
    REFERENCES `dbsistemacafe`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemacafe`.`CajuelasDiaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsistemacafe`.`CajuelasDiaria` ;

CREATE TABLE IF NOT EXISTS `dbsistemacafe`.`CajuelasDiaria` (
  `idCajuelasDiaria` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL NOT NULL,
  `fecha` DATE NOT NULL,
  `Trabajador_idTrabajador` INT NOT NULL,
  `cancelado` TINYINT(1) NOT NULL DEFAULT 0,
  `Pagos_idPagos` INT NOT NULL,
  PRIMARY KEY (`idCajuelasDiaria`),
  UNIQUE INDEX `idCajuelasDiaria_UNIQUE` (`idCajuelasDiaria` ASC),
  INDEX `fk_CajuelasDiaria_Trabajador1_idx` (`Trabajador_idTrabajador` ASC),
  INDEX `fk_CajuelasDiaria_Pagos1_idx` (`Pagos_idPagos` ASC),
  CONSTRAINT `fk_CajuelasDiaria_Trabajador1`
    FOREIGN KEY (`Trabajador_idTrabajador`)
    REFERENCES `dbsistemacafe`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CajuelasDiaria_Pagos1`
    FOREIGN KEY (`Pagos_idPagos`)
    REFERENCES `dbsistemacafe`.`Pagos` (`idPagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
